/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package MyProgram;

import static MyProgram.AllFunctions.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author LUCAS FERNANDO
 */
public class Colchon extends javax.swing.JDialog {

    /**
     * Creates new form Colchon
     */
    public Colchon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e){
            cargarDatos();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        LogoUnab = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDollar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        $ = new javax.swing.JLabel();
        txtColchon = new javax.swing.JLabel();
        btnIngreso = new javax.swing.JButton();
        btnRetiro = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel2.setBackground(new java.awt.Color(153, 0, 204));

        LogoUnab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProgram/Image/logounab.png"))); // NOI18N
        LogoUnab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoUnabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoUnab)
                .addContainerGap(1187, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoUnab)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProgram/Image/Home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProgram/Image/Exit.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        btnDollar.setBackground(new java.awt.Color(255, 153, 51));
        btnDollar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProgram/Image/DollarSing.png"))); // NOI18N
        btnDollar.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Tu Colchón");
        jLabel1.setToolTipText("");

        $.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        $.setText("$");

        txtColchon.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtColchon.setText("0.00");

        btnIngreso.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIngreso.setText("Ingresar Plata");
        btnIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresoMouseClicked(evt);
            }
        });

        btnRetiro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRetiro.setText("Retirar Plata");
        btnRetiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetiroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(677, 677, 677)
                        .addComponent(btnHome)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit)
                        .addGap(18, 18, 18)
                        .addComponent(btnDollar))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent($)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtColchon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(btnIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(btnRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent($)
                    .addComponent(txtColchon))
                .addGap(98, 98, 98)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngreso)
                    .addComponent(btnRetiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome)
                    .addComponent(btnExit)
                    .addComponent(btnDollar))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoUnabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoUnabMouseClicked
        if (A_Que_Pag()){
            JOptionPane.showMessageDialog(this,"Volviendo al Menu Principal","",JOptionPane.PLAIN_MESSAGE);
            this.dispose();
            MenuPrincipal1 mp1 = new MenuPrincipal1(null,true);
            mp1.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,"Volviendo al Menu Principal","",JOptionPane.PLAIN_MESSAGE);
            this.dispose();
            MenuPrincipal0 mp0 = new MenuPrincipal0(null,true);
            mp0.setVisible(true);
        }
    }//GEN-LAST:event_LogoUnabMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        if (A_Que_Pag()){
            JOptionPane.showMessageDialog(this,"Volviendo al Menu Principal","",JOptionPane.PLAIN_MESSAGE);
            this.dispose();
            MenuPrincipal1 mp1 = new MenuPrincipal1(null,true);
            mp1.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,"Volviendo al Menu Principal","",JOptionPane.PLAIN_MESSAGE);
            this.dispose();
            MenuPrincipal0 mp0 = new MenuPrincipal0(null,true);
            mp0.setVisible(true);
        }
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresoMouseClicked
        if (!HaySaldo()) {
            JOptionPane.showMessageDialog(this, "No tiene saldo disponible", "Sin saldo", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        try {
            String input = JOptionPane.showInputDialog(this, "Digita la Cantidad de dinero que vas a ingresar", "Ingresar Plata", JOptionPane.PLAIN_MESSAGE);
            if (input == null) return;
        
            int valor = Integer.parseInt(input);
            if (valor <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que cero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
            if (!ValidarIngreso(valor)) {
                JOptionPane.showMessageDialog(this, "No tienes suficiente saldo para este ingreso", "Saldo insuficiente", JOptionPane.ERROR_MESSAGE);
                return;
        }
        
        Ingreso(valor);
        cargarDatos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        }       
    }//GEN-LAST:event_btnIngresoMouseClicked

    private void btnRetiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetiroMouseClicked
        if (!HayColchon()) {
            JOptionPane.showMessageDialog(this, "No tiene saldo en el colchón", "Sin saldo", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        try {
            String input = JOptionPane.showInputDialog(this, "Digita la Cantidad de dinero que vas a retirar", "Retirar Plata", JOptionPane.PLAIN_MESSAGE);
            if (input == null) return; // Si el usuario cancela
        
            int valor = Integer.parseInt(input);
            if (valor <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que cero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
            if (!ValidarRetiro(valor)) {
                JOptionPane.showMessageDialog(this, "No tienes esa cantidad en el colchón", "Fondos insuficientes", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Retiro(valor);
            cargarDatos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_btnRetiroMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        if (CerrarSesion()) {
            JOptionPane.showMessageDialog(this, "Sesión cerrada correctamente", "Cerrar Sesión", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); 
            Login lg = new Login(null,true);
            lg.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Error al cerrar la sesión", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExitMouseClicked

    public void cargarDatos(){
        String linea;
        try (BufferedReader br = new BufferedReader(new FileReader("Datos.csv"))) {
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(";");
                if (datos.length >= 10 && datos[10].equals("1")) {
                   String texto = datos[8];
                   txtColchon.setText(texto);
                }
            }
        } catch (IOException e) {
            System.err.println("Error al leer el archivo: " + e.getMessage());
        }
    };

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colchon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colchon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colchon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colchon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Colchon dialog = new Colchon(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel $;
    private javax.swing.JLabel LogoUnab;
    private javax.swing.JButton btnDollar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnIngreso;
    private javax.swing.JButton btnRetiro;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JLabel txtColchon;
    // End of variables declaration//GEN-END:variables
}
