/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package MyProgram;

import static MyProgram.AllFunctions.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author LUCAS FERNANDO
 */
public class Perfil extends javax.swing.JDialog {

    /**
     * Creates new form Perfil
     */
    public Perfil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e){
            cargarDatos();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        btnHome = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDollar = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        LogoUnab = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        btnSoporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        txtEdad = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JLabel();
        txtRol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(255, 153, 51));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProgram/Image/Home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProgram/Image/Exit.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        btnDollar.setBackground(new java.awt.Color(204, 102, 255));
        btnDollar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProgram/Image/dollar-sign (1).png"))); // NOI18N
        btnDollar.setBorder(null);
        btnDollar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDollarMouseClicked(evt);
            }
        });

        panel2.setBackground(new java.awt.Color(153, 0, 204));

        LogoUnab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProgram/Image/logounab.png"))); // NOI18N
        LogoUnab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoUnabMouseClicked(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Informacion Personal");

        btnSoporte.setBackground(new java.awt.Color(153, 0, 204));
        btnSoporte.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSoporte.setForeground(new java.awt.Color(255, 255, 255));
        btnSoporte.setText("Soporte");
        btnSoporte.setToolTipText("");
        btnSoporte.setBorder(null);
        btnSoporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSoporteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoUnab)
                .addGap(191, 191, 191)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 455, Short.MAX_VALUE)
                .addComponent(btnSoporte)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(LogoUnab)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Title)
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSoporte)
                .addGap(39, 39, 39))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nombre Completo:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Correo:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Edad:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Carrera:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Rol:");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtEdad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtEdad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtCarrera.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtRol.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(476, 476, 476)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addGap(18, 18, 18)
                .addComponent(btnDollar)
                .addGap(676, 676, 676))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(txtNombre)
                        .addGap(18, 18, 18)
                        .addComponent(txtCorreo)
                        .addGap(18, 18, 18)
                        .addComponent(txtEdad)
                        .addGap(18, 18, 18)
                        .addComponent(txtCarrera)
                        .addGap(18, 18, 18)
                        .addComponent(txtRol)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHome))
                    .addComponent(btnDollar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        if (A_Que_Pag()){
            JOptionPane.showMessageDialog(this,"Volviendo al Menu Principal","",JOptionPane.PLAIN_MESSAGE);
            this.dispose();
            MenuPrincipal1 mp1 = new MenuPrincipal1(null,true);
            mp1.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,"Volviendo al Menu Principal","",JOptionPane.PLAIN_MESSAGE);
            this.dispose();
            MenuPrincipal0 mp0 = new MenuPrincipal0(null,true);
            mp0.setVisible(true);
        }
    }//GEN-LAST:event_btnHomeMouseClicked

    private void LogoUnabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoUnabMouseClicked
        if (A_Que_Pag()){
            JOptionPane.showMessageDialog(this,"Volviendo al Menu Principal","",JOptionPane.PLAIN_MESSAGE);
            this.dispose();
            MenuPrincipal1 mp1 = new MenuPrincipal1(null,true);
            mp1.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,"Volviendo al Menu Principal","",JOptionPane.PLAIN_MESSAGE);
            this.dispose();
            MenuPrincipal0 mp0 = new MenuPrincipal0(null,true);
            mp0.setVisible(true);
        }
    }//GEN-LAST:event_LogoUnabMouseClicked

    private void btnDollarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDollarMouseClicked
        try {
            // Validar saldo
            if (!HaySaldo()) {
                JOptionPane.showMessageDialog(this, "No tiene saldo disponible", "Sin saldo", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
           // Obtener valor a transferir
            String inputValor = JOptionPane.showInputDialog(this, "Digita la Cantidad de dinero que vas a transferir", "Transferir Plata", JOptionPane.PLAIN_MESSAGE);
            if (inputValor == null) return; // Si el usuario cancela
        
            int valor = Integer.parseInt(inputValor);
            if (valor <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que cero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
            // Validar que tenga suficiente saldo
            if (!ValidarSaldoSuficiente(valor)) {
                JOptionPane.showMessageDialog(this, "No tienes suficiente saldo para esta transferencia", "Saldo insuficiente", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Obtener usuario destino
            String destino = JOptionPane.showInputDialog(this, "Ingresa el usuario al que vas a transferir", "Transferir Plata", JOptionPane.PLAIN_MESSAGE);
            if (destino == null || destino.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un usuario destino", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
            // Validar que no sea el mismo usuario
            if (EsUsuarioActual(destino)) {
                JOptionPane.showMessageDialog(this, "No puedes transferirte a ti mismo", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
            // Validar que exista el usuario destino
            if (!ExisteUsuario(destino)) {
                JOptionPane.showMessageDialog(this, "El usuario destino no existe", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
            // Realizar transferencia
            if (EnviarDinero(valor, destino)) {
                JOptionPane.showMessageDialog(this, "Transferencia realizada con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al realizar la transferencia", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDollarMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        if (CerrarSesion()) {
            JOptionPane.showMessageDialog(this, "Sesión cerrada correctamente", "Cerrar Sesión", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); 
            Login lg = new Login(null,true);
            lg.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Error al cerrar la sesión", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnSoporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSoporteMouseClicked
        JOptionPane.showMessageDialog(this, "Si necesitas ayuda de soporte de este sistema, manda un mensaje al siguiente correo:\n lardila329@unab.edu.co","Soporte",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSoporteMouseClicked
    
    public void cargarDatos(){
        String linea;
        try (BufferedReader br = new BufferedReader(new FileReader("Datos.csv"))) {
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(";");
                if (datos.length >= 10 && datos[10].equals("1")) {
                    String nombre = datos[0];
                    String correo = datos[1];
                    String edad = datos[2];
                    String carrera = datos[3];
                    String Rol = (datos[9].equals("1"))?("Administrador"):("Estudiante");
                    txtNombre.setText(nombre);
                    txtCorreo.setText(correo);
                    txtEdad.setText(edad);
                    txtCarrera.setText(carrera);
                    txtRol.setText(Rol);
                }
            }
        } catch (IOException e) {
            System.err.println("Error al leer el archivo: " + e.getMessage());
        }
    };
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Perfil dialog = new Perfil(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoUnab;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnDollar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSoporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JLabel txtCarrera;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtEdad;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtRol;
    // End of variables declaration//GEN-END:variables
}
